esc listener
tainkrios/window-project pull request #3
Opened 2022-04-25 16:27 UTC by tainkrios

2022-04-25 16:37 UTC, andrey-kudinov requested changes
Посмотри пж два небольших замечания

2022-04-25 16:37 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +          modal: HTMLElement = document.querySelector(modalSelector),
Эти отступы здесь специально или случайно добавил?

2022-04-25 16:37 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +          modal: HTMLElement = document.querySelector(modalSelector),
Эти отступы здесь специально или случайно добавил?

2022-04-25 16:37 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +        document.body.style.overflow = ''
У тебя есть функция для закрытия модалки

2022-04-26 07:42 UTC, andrey-kudinov requested changes
Пж посмотри комментарии и внеси соответствующие правки

2022-04-26 07:42 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +      let statusMessage = document.createElement('div')
Переменная у тебя не переприсваивается, пж используй const

2022-04-26 07:42 UTC, andrey-kudinov commented on src/ts/modules/forms.ts
> +      form.appendChild(statusMessage)
.appendChild считается немного устаревшим
Большой разницы нет, но можно использовать просто .append

2022-04-26 07:42 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +// export { modals }
Пж удали комментарий, если он не нужен

2022-04-26 07:42 UTC, andrey-kudinov commented on src/ts/modules/modules.js
> +import { forms } from './forms'
Здесь и на первых двух строчках можно сразу экспортировать
export { form } from './forms'
Тогда последние три строчки не нужны

2022-04-26 10:55 UTC, andrey-kudinov commented on src/ts/modules/modules.js
> +// export { modals, tabs, forms }
Пж удали комментарий, если он тебе больше не нужен

2022-04-26 10:57 UTC, tainkrios commented on src/ts/modules/modules.js
> +// export { modals, tabs, forms }
уже

2022-04-26 10:58 UTC, andrey-kudinov approved these changes

2022-04-26 12:17 UTC, andrey-kudinov approved these changes

2022-04-26 12:18 UTC, merged